version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:7.12.1
    container_name: elasticsearch
    restart: "no"
    volumes:
      - ./data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
      cluster.name: elasticsearch
    ports:
      - '9200:9200'
    networks:
      - default_network

  kibana:
    image: kibana:7.12.1
    container_name: kibana
    restart: "no"
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - default_network

networks:
  default_network:
    external: true
